/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoltsRouteImport } from './routes/bolts'
import { Route as PlateRouteImport } from './routes/plate'
import { Route as UnitsRouteImport } from './routes/units'
import { Route as BoltsSlugRouteImport } from './routes/bolts.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoltsRoute = BoltsRouteImport.update({
  id: '/bolts',
  path: '/bolts',
  getParentRoute: () => rootRouteImport,
} as any)
const PlateRoute = PlateRouteImport.update({
  id: '/plate',
  path: '/plate',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)
const BoltsSlugRoute = BoltsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BoltsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bolts': typeof BoltsRouteWithChildren
  '/plate': typeof PlateRoute
  '/units': typeof UnitsRoute
  '/bolts/$slug': typeof BoltsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bolts': typeof BoltsRouteWithChildren
  '/plate': typeof PlateRoute
  '/units': typeof UnitsRoute
  '/bolts/$slug': typeof BoltsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bolts': typeof BoltsRouteWithChildren
  '/plate': typeof PlateRoute
  '/units': typeof UnitsRoute
  '/bolts/$slug': typeof BoltsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bolts' | '/plate' | '/units' | '/bolts/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bolts' | '/plate' | '/units' | '/bolts/$slug'
  id: '__root__' | '/' | '/bolts' | '/plate' | '/units' | '/bolts/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoltsRoute: typeof BoltsRouteWithChildren
  PlateRoute: typeof PlateRoute
  UnitsRoute: typeof UnitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bolts': {
      id: '/bolts'
      path: '/bolts'
      fullPath: '/bolts'
      preLoaderRoute: typeof BoltsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plate': {
      id: '/plate'
      path: '/plate'
      fullPath: '/plate'
      preLoaderRoute: typeof PlateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bolts/$slug': {
      id: '/bolts/$slug'
      path: '/$slug'
      fullPath: '/bolts/$slug'
      preLoaderRoute: typeof BoltsSlugRouteImport
      parentRoute: typeof BoltsRoute
    }
  }
}

interface BoltsRouteChildren {
  BoltsSlugRoute: typeof BoltsSlugRoute
}

const BoltsRouteChildren: BoltsRouteChildren = {
  BoltsSlugRoute: BoltsSlugRoute,
}

const BoltsRouteWithChildren = BoltsRoute._addFileChildren(BoltsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoltsRoute: BoltsRouteWithChildren,
  PlateRoute: PlateRoute,
  UnitsRoute: UnitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
